version: "3.9"

services:
  db:
    image: mysql:5.7.30
    container_name: archdashDB
    volumes:
      - ./data/arch:/var/lib/mysql
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "archdash"
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: archdashAPI
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
