# Generated by Django 3.2 on 2022-04-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisparameter',
            name='analysis_portfolio_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_portfolio_category', to='api.analysisportfoliocategory'),
        ),
    ]
