# Generated by Django 3.2 on 2022-04-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_analysisparameter_analysis_portfolio_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervalue',
            name='answer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_types', to='api.answertype'),
        ),
    ]
