# Generated by Django 3.2 on 2022-04-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answervalue_answer_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisportfoliocategory',
            name='analysis_portfolio_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.analysisportfolio'),
            preserve_default=False,
        ),
    ]
