# Generated by Django 3.2 on 2022-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_analysisportfoliocategory_analysis_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisportfoliocategory',
            name='analysis_portfolio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_portfolios', to='api.analysisportfolio'),
        ),
    ]
