# Generated by Django 3.2 on 2022-05-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_analysisvalue_analysis_parameter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisvalue',
            name='analysis_parameter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_parameter_value', to='api.analysisparameter'),
        ),
    ]
