# Generated by Django 3.2 on 2022-05-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_analysisvalue_analysis_parameter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='analysisvalue',
            name='answer_value_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_values', to='api.answervalue'),
            preserve_default=False,
        ),
    ]
